include: package:altive_lints/altive_lints.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    specify_nonobvious_local_variable_types: ignore
  plugins:
    - custom_lint
  exclude: "**/gen/*.dart"
