name: flutter_app
description: A Flutter app.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  altive_lints: ^1.16.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_hooks: ^0.20.5
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  gap: ^3.0.1
  flutter_gpu:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true